UPDATE HCUP.dbo.HCUP_MCC_2012 SET AGE_GROUP ='65_74' WHERE AGE >= 65 AND AGE <= 74；
UPDATE HCUP.dbo.HCUP_MCC_2012 SET AGE_GROUP ='75_84' WHERE AGE >= 75 AND AGE <= 84;
UPDATE HCUP.dbo.HCUP_MCC_2012 SET AGE_GROUP ='ABOVE_85' WHERE AGE >= 85;
UPDATE HCUP.dbo.HCUP_MCC_2012 SET ETHNICITY='NON_HISPANIC_WHITE' WHERE RACE = '1' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2012 SET ETHNICITY='NON_HISPANIC_BLACK' WHERE RACE = '2' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2012 SET ETHNICITY='ASIAN_PI' WHERE RACE = '4' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2012 SET ETHNICITY='HISPANIC' WHERE HISPANTIC = '1';

UPDATE HCUP.dbo.HCUP_MCC_2011 SET AGE_GROUP ='65_74' WHERE AGE >= 65 AND AGE <= 74；
UPDATE HCUP.dbo.HCUP_MCC_2011 SET AGE_GROUP ='75_84' WHERE AGE >= 75 AND AGE <= 84;
UPDATE HCUP.dbo.HCUP_MCC_2011 SET AGE_GROUP ='ABOVE_85' WHERE AGE >= 85;
UPDATE HCUP.dbo.HCUP_MCC_2011 SET ETHNICITY='NON_HISPANIC_WHITE' WHERE RACE = '1' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2011 SET ETHNICITY='NON_HISPANIC_BLACK' WHERE RACE = '2' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2011 SET ETHNICITY='ASIAN_PI' WHERE RACE = '4' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2011 SET ETHNICITY='HISPANIC' WHERE HISPANTIC = '1';

UPDATE HCUP.dbo.HCUP_MCC_2010 SET AGE_GROUP ='65_74' WHERE AGE >= 65 AND AGE <= 74；
UPDATE HCUP.dbo.HCUP_MCC_2010 SET AGE_GROUP ='75_84' WHERE AGE >= 75 AND AGE <= 84;
UPDATE HCUP.dbo.HCUP_MCC_2010 SET AGE_GROUP ='ABOVE_85' WHERE AGE >= 85;
UPDATE HCUP.dbo.HCUP_MCC_2010 SET ETHNICITY='NON_HISPANIC_WHITE' WHERE RACE = '1' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2010 SET ETHNICITY='NON_HISPANIC_BLACK' WHERE RACE = '2' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2010 SET ETHNICITY='ASIAN_PI' WHERE RACE = '4' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2010 SET ETHNICITY='HISPANIC' WHERE HISPANTIC = '1';

UPDATE HCUP.dbo.HCUP_MCC_2009 SET AGE_GROUP ='65_74' WHERE AGE >= 65 AND AGE <= 74；
UPDATE HCUP.dbo.HCUP_MCC_2009 SET AGE_GROUP ='75_84' WHERE AGE >= 75 AND AGE <= 84;
UPDATE HCUP.dbo.HCUP_MCC_2009 SET AGE_GROUP ='ABOVE_85' WHERE AGE >= 85;
UPDATE HCUP.dbo.HCUP_MCC_2009 SET ETHNICITY='NON_HISPANIC_WHITE' WHERE RACE = '1' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2009 SET ETHNICITY='NON_HISPANIC_BLACK' WHERE RACE = '2' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2009 SET ETHNICITY='ASIAN_PI' WHERE RACE = '4' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2009 SET ETHNICITY='HISPANIC' WHERE HISPANTIC = '1';

UPDATE HCUP.dbo.HCUP_MCC_2008 SET AGE_GROUP ='65_74' WHERE AGE >= 65 AND AGE <= 74；
UPDATE HCUP.dbo.HCUP_MCC_2008 SET AGE_GROUP ='75_84' WHERE AGE >= 75 AND AGE <= 84;
UPDATE HCUP.dbo.HCUP_MCC_2008 SET AGE_GROUP ='ABOVE_85' WHERE AGE >= 85;
UPDATE HCUP.dbo.HCUP_MCC_2008 SET ETHNICITY='NON_HISPANIC_WHITE' WHERE RACE = '1' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2008 SET ETHNICITY='NON_HISPANIC_BLACK' WHERE RACE = '2' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2008 SET ETHNICITY='ASIAN_PI' WHERE RACE = '4' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2008 SET ETHNICITY='HISPANIC' WHERE HISPANTIC = '1';

UPDATE HCUP.dbo.HCUP_MCC_2007 SET AGE_GROUP ='65_74' WHERE AGE >= 65 AND AGE <= 74；
UPDATE HCUP.dbo.HCUP_MCC_2007 SET AGE_GROUP ='75_84' WHERE AGE >= 75 AND AGE <= 84;
UPDATE HCUP.dbo.HCUP_MCC_2007 SET AGE_GROUP ='ABOVE_85' WHERE AGE >= 85;
UPDATE HCUP.dbo.HCUP_MCC_2007 SET ETHNICITY='NON_HISPANIC_WHITE' WHERE RACE = '1' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2007 SET ETHNICITY='NON_HISPANIC_BLACK' WHERE RACE = '2' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2007 SET ETHNICITY='ASIAN_PI' WHERE RACE = '4' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2007 SET ETHNICITY='HISPANIC' WHERE HISPANTIC = '1';

UPDATE HCUP.dbo.HCUP_MCC_2006 SET AGE_GROUP ='65_74' WHERE AGE >= 65 AND AGE <= 74；
UPDATE HCUP.dbo.HCUP_MCC_2006 SET AGE_GROUP ='75_84' WHERE AGE >= 75 AND AGE <= 84;
UPDATE HCUP.dbo.HCUP_MCC_2006 SET AGE_GROUP ='ABOVE_85' WHERE AGE >= 85;
UPDATE HCUP.dbo.HCUP_MCC_2006 SET ETHNICITY='NON_HISPANIC_WHITE' WHERE RACE = '1' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2006 SET ETHNICITY='NON_HISPANIC_BLACK' WHERE RACE = '2' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2006 SET ETHNICITY='ASIAN_PI' WHERE RACE = '4' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2006 SET ETHNICITY='HISPANIC' WHERE HISPANTIC = '1';

UPDATE HCUP.dbo.HCUP_MCC_2005 SET AGE_GROUP ='65_74' WHERE AGE >= 65 AND AGE <= 74；
UPDATE HCUP.dbo.HCUP_MCC_2005 SET AGE_GROUP ='75_84' WHERE AGE >= 75 AND AGE <= 84;
UPDATE HCUP.dbo.HCUP_MCC_2005 SET AGE_GROUP ='ABOVE_85' WHERE AGE >= 85;
UPDATE HCUP.dbo.HCUP_MCC_2005 SET ETHNICITY='NON_HISPANIC_WHITE' WHERE RACE = '1' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2005 SET ETHNICITY='NON_HISPANIC_BLACK' WHERE RACE = '2' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2005 SET ETHNICITY='ASIAN_PI' WHERE RACE = '4' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2005 SET ETHNICITY='HISPANIC' WHERE HISPANTIC = '1';

UPDATE HCUP.dbo.HCUP_MCC_2004 SET AGE_GROUP ='65_74' WHERE AGE >= 65 AND AGE <= 74；
UPDATE HCUP.dbo.HCUP_MCC_2004 SET AGE_GROUP ='75_84' WHERE AGE >= 75 AND AGE <= 84;
UPDATE HCUP.dbo.HCUP_MCC_2004 SET AGE_GROUP ='ABOVE_85' WHERE AGE >= 85;
UPDATE HCUP.dbo.HCUP_MCC_2004 SET ETHNICITY='NON_HISPANIC_WHITE' WHERE RACE = '1' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2004 SET ETHNICITY='NON_HISPANIC_BLACK' WHERE RACE = '2' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2004 SET ETHNICITY='ASIAN_PI' WHERE RACE = '4' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2004 SET ETHNICITY='HISPANIC' WHERE HISPANTIC = '1';

UPDATE HCUP.dbo.HCUP_MCC_2003 SET AGE_GROUP ='65_74' WHERE AGE >= 65 AND AGE <= 74；
UPDATE HCUP.dbo.HCUP_MCC_2003 SET AGE_GROUP ='75_84' WHERE AGE >= 75 AND AGE <= 84;
UPDATE HCUP.dbo.HCUP_MCC_2003 SET AGE_GROUP ='ABOVE_85' WHERE AGE >= 85;
UPDATE HCUP.dbo.HCUP_MCC_2003 SET ETHNICITY='NON_HISPANIC_WHITE' WHERE RACE = '1' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2003 SET ETHNICITY='NON_HISPANIC_BLACK' WHERE RACE = '2' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2003 SET ETHNICITY='ASIAN_PI' WHERE RACE = '4' AND HISPANTIC = '0';
UPDATE HCUP.dbo.HCUP_MCC_2003 SET ETHNICITY='HISPANIC' WHERE HISPANTIC = '1';